apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredIPFiltering
metadata:
  name: svc-must-have-ip-filtering
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Service